// node scripts/dev/nav-map.js
// Regenerates .claude/docs/nav-map.md: where things live in src/. Names only,
// no line numbers, so the map stays true between runs (grep -n a name to land
// on it). Run at session end, or after adding/renaming files, components or
// IPC channels.
const fs = require("fs");
const path = require("path");

const REPO = path.join(__dirname, "..", "..");
const OUT = path.join(REPO, ".claude", "docs", "nav-map.md");
const BIG = 1000; // files at least this long get a per-section outline

const rel = (f) => path.relative(REPO, f).split(path.sep).join("/");
function walk(dir, acc = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { if (e.name !== "__tests__" && e.name !== "node_modules") walk(p, acc); }
    else if (/\.(js|jsx|ts|tsx)$/.test(e.name) && !/\.test\./.test(e.name)) acc.push(p);
  }
  return acc;
}
const files = walk(path.join(REPO, "src")).sort();
const read = (f) => fs.readFileSync(f, "utf8").replace(/\r\n/g, "\n").split("\n");

// First sentence of the file's header comment, if it has one.
function summary(lines) {
  for (const raw of lines.slice(0, 15)) {
    const l = raw.trim();
    if (!l || /^("use strict"|'use strict'|\/\*\*?$)/.test(l)) continue;
    const m = l.match(/^(?:\/\/|\/?\*+)\s*(.+?)\s*(?:\*\/)?$/);
    if (!m || /^(import|const|require|eslint)/.test(m[1])) return "";
    return m[1].replace(/\s+/g, " ").split(/(?<=\.)\s/)[0].slice(0, 140);
  }
  return "";
}

const DECL = /^(?:export\s+)?(?:default\s+)?(?:async\s+)?function\s*\*?\s*(\w+)|^(?:export\s+)?const\s+(\w+)\s*=\s*(?:React\.)?(?:memo\(|forwardRef\(|async\s*)?(?:\(|function\b|\w+\s*=>)/;
const BANNER = /^\s*\/\/\s*(?:[═─=#-]{3,})\s*(.+?)\s*(?:[═─=#-]{3,})?\s*$/;
const IPC = /ipcMain\.(?:handle|on)\(\s*["'`]([^"'`]+)["'`]/;

function outline(lines) {
  const groups = [{ title: "(top)", names: [], ipc: [] }];
  for (const l of lines) {
    const b = l.match(BANNER);
    if (b && /[A-Za-z]/.test(b[1])) { groups.push({ title: b[1], names: [], ipc: [] }); continue; }
    const d = l.match(DECL);
    if (d) groups[groups.length - 1].names.push(d[1] || d[2]);
    const i = l.match(IPC);
    if (i) groups[groups.length - 1].ipc.push(i[1]);
  }
  return groups.filter((g) => g.names.length || g.ipc.length);
}

// IPC: preload method -> channel -> file that handles it.
const handlers = {};
for (const f of files) for (const l of read(f)) { const m = l.match(IPC); if (m) handlers[m[1]] = rel(f); }
// Each bridge method is a 2-space-indented key of the exposed object; its
// first ipcRenderer call says which channel it uses and in which direction.
const bridge = [];
let entry = null;
const flush = () => {
  if (!entry) return;
  const c = entry.body.match(/ipcRenderer\.(\w+)\(\s*["'`]([^"'`]+)["'`]/);
  if (!c) return;
  const [, kind, ch] = c;
  const where = /^(invoke|send|sendSync)$/.test(kind) ? `(${handlers[ch] || "no handler found"})`
    : /^(on|once)$/.test(kind) ? "(event sent by main)" : "(removes listeners)";
  bridge.push(`${entry.name} → ${ch} ${where}`);
};
for (const l of read(path.join(REPO, "src", "main", "preload.js"))) {
  const k = l.match(/^ {2}(\w+)\s*:/);
  if (k) { flush(); entry = { name: k[1], body: l }; } else if (entry) entry.body += "\n" + l;
}
flush();

const out = [
  "# Navigation map (generated)",
  "",
  "Generated by `node scripts/dev/nav-map.js`; don't edit by hand. **Grep this file, don't read it",
  "whole.** It lists names only: `grep -n <name> <file>` to land on one.",
  "",
  `## Big files (${BIG}+ lines): top-level names by section`,
  "",
  "Sections come from the file's own `// ==== TITLE ====` banners where it has them; inner",
  "handlers of a giant component aren't listed (grep the component, then read from there).",
  "",
];
for (const f of files) {
  const lines = read(f);
  if (lines.length < BIG) continue;
  out.push(`### ${rel(f)} (${lines.length} lines)`);
  for (const g of outline(lines)) {
    const parts = [];
    if (g.names.length) parts.push(g.names.join(", "));
    if (g.ipc.length) parts.push(`IPC: ${g.ipc.join(", ")}`);
    out.push(`- **${g.title}**: ${parts.join(" · ")}`);
  }
  out.push("");
}
out.push("## Every source file", "", "Line count and the first line of its header comment.", "");
for (const f of files) {
  const lines = read(f);
  const s = summary(lines);
  out.push(`- \`${rel(f)}\` (${lines.length})${s ? `: ${s}` : ""}`);
}
out.push("", "## window.clipflow bridge: method → IPC channel (handler file)", "");
for (const b of bridge) out.push(`- ${b}`);
out.push("");

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, out.join("\n"));
console.log(`wrote ${rel(OUT)}: ${files.length} files, ${bridge.length} bridge methods, ${Object.keys(handlers).length} IPC channels`);
